#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory


source ../../scripts/pyInstall.sh

pyincludeswithNumpy > Make/options.template
echo -e "\n" >> Make/options.template
pylibs -rpath >> Make/options.template
echo -e "\n" >> Make/options.template
cat Make/options.temp >> Make/options.template

rm -r lnInclude
wmakeLnIncludeAll 
copyPythonIncs lnInclude/

conan install . -s compiler=gcc -s compiler.libcxx=libstdc++11 --build
wmake libso
