"""finite volume calculus"""

from typing import overload

import pybFoam.pybFoam_core


@overload
def grad(vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def grad(vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def grad(vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def grad(vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.tmp_surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.tmp_surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def div(vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def div(vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def div(arg: pybFoam.pybFoam_core.surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.surfaceTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_surfaceTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.surfaceSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_surfaceSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def interpolate(vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def interpolate(vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def interpolate(vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def interpolate(vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def interpolate(vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceTensorField: ...

@overload
def interpolate(vf: pybFoam.pybFoam_core.tmp_volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceTensorField: ...

@overload
def interpolate(vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceSymmTensorField: ...

@overload
def interpolate(vf: pybFoam.pybFoam_core.tmp_volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceSymmTensorField: ...

@overload
def flux(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def flux(arg: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def flux(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, key: str | None = None) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def flux(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volScalarField, *, key: str | None = None) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def flux(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, key: str | None = None) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def flux(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.tmp_volVectorField, *, key: str | None = None) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def snGrad(vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def snGrad(vf: pybFoam.pybFoam_core.tmp_volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def snGrad(vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def snGrad(vf: pybFoam.pybFoam_core.tmp_volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def reconstruct(arg: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def reconstruct(arg: pybFoam.pybFoam_core.tmp_surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def reconstruct(arg: pybFoam.pybFoam_core.surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def reconstruct(arg: pybFoam.pybFoam_core.tmp_surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def surfaceSum(arg: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def surfaceSum(arg: pybFoam.pybFoam_core.tmp_surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def surfaceSum(arg: pybFoam.pybFoam_core.surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def surfaceSum(arg: pybFoam.pybFoam_core.tmp_surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def ddtCorr(arg0: pybFoam.pybFoam_core.volVectorField, arg1: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def ddtCorr(arg0: pybFoam.pybFoam_core.volVectorField, arg1: pybFoam.pybFoam_core.surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

def meshPhi(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

def makeRelative(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> None: ...

def makeAbsolute(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> None: ...

def correctUf(arg0: pybFoam.pybFoam_core.surfaceVectorField, arg1: pybFoam.pybFoam_core.volVectorField, arg2: pybFoam.pybFoam_core.surfaceScalarField, /) -> None: ...
