"""finite volume calculus"""

from typing import overload

import pybFoam.pybFoam_core


@overload
def grad(arg: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.tmp_surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def grad(arg: pybFoam.pybFoam_core.tmp_surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def div(arg: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def div(arg: pybFoam.pybFoam_core.surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.surfaceTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_surfaceTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.surfaceSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def div(arg: pybFoam.pybFoam_core.tmp_surfaceSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

@overload
def interpolate(arg: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def interpolate(arg: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def interpolate(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def interpolate(arg: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def interpolate(arg: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_surfaceTensorField: ...

@overload
def interpolate(arg: pybFoam.pybFoam_core.tmp_volTensorField, /) -> pybFoam.pybFoam_core.tmp_surfaceTensorField: ...

@overload
def interpolate(arg: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_surfaceSymmTensorField: ...

@overload
def interpolate(arg: pybFoam.pybFoam_core.tmp_volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_surfaceSymmTensorField: ...

@overload
def flux(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def flux(arg: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def flux(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def flux(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def snGrad(arg: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def snGrad(arg: pybFoam.pybFoam_core.tmp_volScalarField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

@overload
def snGrad(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def snGrad(arg: pybFoam.pybFoam_core.tmp_volVectorField, /) -> pybFoam.pybFoam_core.tmp_surfaceVectorField: ...

@overload
def reconstruct(arg: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def reconstruct(arg: pybFoam.pybFoam_core.tmp_surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_volVectorField: ...

@overload
def reconstruct(arg: pybFoam.pybFoam_core.surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

@overload
def reconstruct(arg: pybFoam.pybFoam_core.tmp_surfaceVectorField, /) -> pybFoam.pybFoam_core.tmp_volTensorField: ...

def ddtCorr(arg0: pybFoam.pybFoam_core.volVectorField, arg1: pybFoam.pybFoam_core.surfaceScalarField, /) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...
