from pybFoam.pybFoam_core import (
    DictionaryGetOrDefaultProxy,
    DictionaryGetProxy,
    Info,
    # polyMesh bindings
    IOobject,
    SolverScalarPerformance,
    SolverSymmTensorPerformance,
    SolverTensorPerformance,
    SolverVectorPerformance,
    SymmTensorInt,
    TensorInt,
    Time,
    VectorInt,
    Word,
    adjustPhi,
    argList,
    boolList,
    computeCFLNumber,
    computeContinuityErrors,
    constrainHbyA,
    constrainPressure,
    createMesh,
    createPhi,
    dictionary,
    dimAcceleration,
    dimArea,
    dimCurrent,
    dimDensity,
    dimEnergy,
    dimensionedScalar,
    dimensionedSymmTensor,
    dimensionedTensor,
    dimensionedVector,
    dimensionSet,
    dimForce,
    dimLength,
    dimless,
    dimLuminousIntensity,
    dimMass,
    dimMoles,
    dimPower,
    dimPressure,
    dimTemperature,
    dimTime,
    dimVelocity,
    dimViscosity,
    dynamicFvMesh,
    entry,
    fileName,
    fvMesh,
    fvScalarMatrix,
    fvSymmTensorMatrix,
    fvTensorMatrix,
    fvVectorMatrix,
    instant,
    instantList,
    keyType,
    labelList,
    mag,
    pimpleControl,
    pisoControl,
    polyBoundaryMesh,
    polyMesh,
    polyPatch,
    scalarField,
    selectTimes,
    setRefCell,
    simpleControl,
    solve,
    sum,
    surfaceScalarField,
    surfaceSymmTensorField,
    surfaceTensorField,
    surfaceVectorField,
    symmTensor,
    symmTensorField,
    tensor,
    tensorField,
    tmp_fvScalarMatrix,
    tmp_fvSymmTensorMatrix,
    tmp_fvTensorMatrix,
    tmp_fvVectorMatrix,
    tmp_scalarField,
    tmp_surfaceScalarField,
    tmp_surfaceSymmTensorField,
    tmp_surfaceTensorField,
    tmp_surfaceVectorField,
    tmp_symmTensorField,
    tmp_tensorField,
    tmp_vectorField,
    tmp_volScalarField,
    tmp_volSymmTensorField,
    tmp_volTensorField,
    tmp_volVectorField,
    uniformDimensionedScalarField,
    uniformDimensionedVectorField,
    vector,
    vectorField,
    volScalarField,
    volSymmTensorField,
    volTensorField,
    volVectorField,
    wordList,
    write,
)

from . import fvc, fvm, meshing, runTimeTables, sampling_bindings, thermo, turbulence, vof
from ._version import __version__

__all__ = [
    # Core dictionary and info types
    "DictionaryGetOrDefaultProxy",
    "DictionaryGetProxy",
    "Info",
    # Mesh and I/O types
    "IOobject",
    "Time",
    "Word",
    "argList",
    "dictionary",
    "entry",
    "fileName",
    "instant",
    "instantList",
    "keyType",
    # Mesh types
    "dynamicFvMesh",
    "fvMesh",
    "polyBoundaryMesh",
    "polyMesh",
    "polyPatch",
    # Solver performance types
    "SolverScalarPerformance",
    "SolverSymmTensorPerformance",
    "SolverTensorPerformance",
    "SolverVectorPerformance",
    # Integer vector/tensor types
    "SymmTensorInt",
    "TensorInt",
    "VectorInt",
    # Basic types
    "boolList",
    "labelList",
    "wordList",
    # Primitive types
    "symmTensor",
    "tensor",
    "vector",
    # Field types
    "scalarField",
    "symmTensorField",
    "tensorField",
    "vectorField",
    # Volume field types
    "volScalarField",
    "volSymmTensorField",
    "volTensorField",
    "volVectorField",
    # Surface field types
    "surfaceScalarField",
    "surfaceSymmTensorField",
    "surfaceTensorField",
    "surfaceVectorField",
    # Uniform dimensioned field types
    "uniformDimensionedScalarField",
    "uniformDimensionedVectorField",
    # Temporary field types
    "tmp_scalarField",
    "tmp_symmTensorField",
    "tmp_tensorField",
    "tmp_vectorField",
    "tmp_volScalarField",
    "tmp_volSymmTensorField",
    "tmp_volTensorField",
    "tmp_volVectorField",
    "tmp_surfaceScalarField",
    "tmp_surfaceSymmTensorField",
    "tmp_surfaceTensorField",
    "tmp_surfaceVectorField",
    # Matrix types
    "fvScalarMatrix",
    "fvSymmTensorMatrix",
    "fvTensorMatrix",
    "fvVectorMatrix",
    "tmp_fvScalarMatrix",
    "tmp_fvSymmTensorMatrix",
    "tmp_fvTensorMatrix",
    "tmp_fvVectorMatrix",
    # Dimensioned types
    "dimensionedScalar",
    "dimensionedSymmTensor",
    "dimensionedTensor",
    "dimensionedVector",
    "dimensionSet",
    # Dimension constants
    "dimAcceleration",
    "dimArea",
    "dimCurrent",
    "dimDensity",
    "dimEnergy",
    "dimForce",
    "dimLength",
    "dimless",
    "dimLuminousIntensity",
    "dimMass",
    "dimMoles",
    "dimPower",
    "dimPressure",
    "dimTemperature",
    "dimTime",
    "dimVelocity",
    "dimViscosity",
    # Solver control types
    "pimpleControl",
    "pisoControl",
    "simpleControl",
    # Utility functions
    "adjustPhi",
    "computeCFLNumber",
    "computeContinuityErrors",
    "constrainHbyA",
    "constrainPressure",
    "createMesh",
    "createPhi",
    "mag",
    "selectTimes",
    "setRefCell",
    "solve",
    "sum",
    "write",
    # Submodules
    "fvc",
    "fvm",
    "meshing",
    "runTimeTables",
    "sampling_bindings",
    "thermo",
    "turbulence",
    "vof",
    # Version
    "__version__",
]
