#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory

echo $PWD

./pybFoam_core/Allwmake
./runTimeTables/Allwmake
./fvc/Allwmake
./thermo/Allwmake
./turbulence/Allwmake

stubgen -m pybFoam_core -o .
stubgen -m fvc -o .
stubgen -m runTimeTables -o .
stubgen -m thermo -o .
stubgen -m turbulence -o .
# stubgen -m pybFoam_fvc -o .
