#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory

./pybFoam_core/Allwmake

./runTimeTables/Allwmake

stubgen -m pybFoam_core -o .
stubgen -m runTimeTables -o .
