from typing import Any

def div(*args, **kwargs) -> Any: ...
def flux(*args, **kwargs) -> Any: ...
def grad(*args, **kwargs) -> Any: ...
def interpolate(*args, **kwargs) -> Any: ...
def laplacian(*args, **kwargs) -> Any: ...
