"""
available runtime tables
"""
from __future__ import annotations
__all__ = ['Function1', 'fvPatchScalarField', 'fvPatchSphericalTensorField', 'fvPatchSymmTensorField', 'fvPatchTensorField', 'fvPatchVectorField']
def Function1() -> list[str]:
    ...
def fvPatchScalarField() -> list[str]:
    ...
def fvPatchSphericalTensorField() -> list[str]:
    ...
def fvPatchSymmTensorField() -> list[str]:
    ...
def fvPatchTensorField() -> list[str]:
    ...
def fvPatchVectorField() -> list[str]:
    ...
