def Function1() -> list[str]: ...
def fvPatchScalarField() -> list[str]: ...
def fvPatchSphericalTensorField() -> list[str]: ...
def fvPatchSymmTensorField() -> list[str]: ...
def fvPatchTensorField() -> list[str]: ...
def fvPatchVectorField() -> list[str]: ...
