from typing import List

def Function1() -> List[str]: ...
def fvPatchScalarField() -> List[str]: ...
def fvPatchSphericalTensorField() -> List[str]: ...
def fvPatchSymmTensorField() -> List[str]: ...
def fvPatchTensorField() -> List[str]: ...
def fvPatchVectorField() -> List[str]: ...
