from typing import Any

class basicThermo:
    def __init__(self, *args, **kwargs) -> None: ...
    def Cp(self, *args, **kwargs) -> Any: ...
    def Cv(self, *args, **kwargs) -> Any: ...
    def T(self, *args, **kwargs) -> Any: ...
    def alphaEff(self, *args, **kwargs) -> Any: ...
    def from_registry(self, *args, **kwargs) -> Any: ...
    def he(self, *args, **kwargs) -> Any: ...
    def kappa(self, *args, **kwargs) -> Any: ...
    def kappaEff(self, *args, **kwargs) -> Any: ...
    def p(self, *args, **kwargs) -> Any: ...
    def rho(self, *args, **kwargs) -> Any: ...

class fluidThermo(basicThermo):
    def __init__(self, *args, **kwargs) -> None: ...
    def from_registry(self, *args, **kwargs) -> Any: ...

class solidThermo(basicThermo):
    def __init__(self, *args, **kwargs) -> None: ...
    def from_registry(self, *args, **kwargs) -> Any: ...
