"""
openfoam turbulence package
"""
from __future__ import annotations
import pybFoam_core
import typing
__all__: list[str] = ['compressibleTurbulenceModel', 'incompressibleTurbulenceModel', 'singlePhaseTransportModel']
class compressibleTurbulenceModel:
    @staticmethod
    def from_registry(arg0: pybFoam_core.fvMesh) -> compressibleTurbulenceModel:
        ...
    def R(self) -> pybFoam_core.tmp_volSymmTensorField:
        ...
    def U(self) -> pybFoam_core.volVectorField:
        ...
    def alphaRhoPhi(self) -> pybFoam_core.surfaceScalarField:
        ...
    @typing.overload
    def devRhoReff(self) -> pybFoam_core.tmp_volSymmTensorField:
        ...
    @typing.overload
    def devRhoReff(self, arg0: pybFoam_core.volVectorField) -> pybFoam_core.tmp_volSymmTensorField:
        ...
    def divDevRhoReff(self, arg0: pybFoam_core.volVectorField) -> pybFoam_core.tmp_fvVectorMatrix:
        ...
    def epsilon(self) -> pybFoam_core.tmp_volScalarField:
        ...
    def k(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def mu(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def mu(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def muEff(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def muEff(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def mut(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def mut(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def nu(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def nu(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def nuEff(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def nuEff(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def nut(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def nut(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    def omega(self) -> pybFoam_core.tmp_volScalarField:
        ...
    def phi(self) -> pybFoam_core.tmp_surfaceScalarField:
        ...
class incompressibleTurbulenceModel:
    @staticmethod
    def New(U: pybFoam_core.volVectorField, phi: pybFoam_core.surfaceScalarField, transportModel: singlePhaseTransportModel, propertiesName: pybFoam_core.Word = ...) -> incompressibleTurbulenceModel:
        ...
    @staticmethod
    def from_registry(arg0: pybFoam_core.fvMesh) -> incompressibleTurbulenceModel:
        ...
    def R(self) -> pybFoam_core.tmp_volSymmTensorField:
        ...
    def U(self) -> pybFoam_core.volVectorField:
        ...
    def alphaRhoPhi(self) -> pybFoam_core.surfaceScalarField:
        ...
    def correct(self) -> None:
        ...
    @typing.overload
    def devRhoReff(self) -> pybFoam_core.tmp_volSymmTensorField:
        ...
    @typing.overload
    def devRhoReff(self, arg0: pybFoam_core.volVectorField) -> pybFoam_core.tmp_volSymmTensorField:
        ...
    def divDevReff(self, arg0: pybFoam_core.volVectorField) -> pybFoam_core.tmp_fvVectorMatrix:
        ...
    def epsilon(self) -> pybFoam_core.tmp_volScalarField:
        ...
    def k(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def mu(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def mu(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def muEff(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def muEff(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def mut(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def mut(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def nu(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def nu(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def nuEff(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def nuEff(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    @typing.overload
    def nut(self) -> pybFoam_core.tmp_volScalarField:
        ...
    @typing.overload
    def nut(self, arg0: typing.SupportsInt) -> pybFoam_core.tmp_scalarField:
        ...
    def omega(self) -> pybFoam_core.tmp_volScalarField:
        ...
    def phi(self) -> pybFoam_core.tmp_surfaceScalarField:
        ...
class singlePhaseTransportModel:
    def __init__(self, U: pybFoam_core.volVectorField, phi: pybFoam_core.surfaceScalarField) -> None:
        ...
    def correct(self) -> None:
        ...
