class compressibleTurbulenceModel:
    def __init__(self, *args, **kwargs) -> None: ...
    def R(self, *args, **kwargs): ...
    def U(self, *args, **kwargs): ...
    def alphaRhoPhi(self, *args, **kwargs): ...
    def devRhoReff(self, *args, **kwargs): ...
    def divDevRhoReff(self, *args, **kwargs): ...
    def epsilon(self, *args, **kwargs): ...
    @staticmethod
    def from_registry(arg0) -> compressibleTurbulenceModel: ...
    def k(self, *args, **kwargs): ...
    def mu(self, *args, **kwargs): ...
    def muEff(self, *args, **kwargs): ...
    def mut(self, *args, **kwargs): ...
    def nu(self, *args, **kwargs): ...
    def nuEff(self, *args, **kwargs): ...
    def nut(self, *args, **kwargs): ...
    def omega(self, *args, **kwargs): ...
    def phi(self, *args, **kwargs): ...
    def y(self, *args, **kwargs): ...

class incompressibleTurbulenceModel:
    def __init__(self, *args, **kwargs) -> None: ...
    def R(self, *args, **kwargs): ...
    def U(self, *args, **kwargs): ...
    def alphaRhoPhi(self, *args, **kwargs): ...
    def devRhoReff(self, *args, **kwargs): ...
    def divDevReff(self, *args, **kwargs): ...
    def epsilon(self, *args, **kwargs): ...
    @staticmethod
    def from_registry(arg0) -> incompressibleTurbulenceModel: ...
    def k(self, *args, **kwargs): ...
    def mu(self, *args, **kwargs): ...
    def muEff(self, *args, **kwargs): ...
    def mut(self, *args, **kwargs): ...
    def nu(self, *args, **kwargs): ...
    def nuEff(self, *args, **kwargs): ...
    def nut(self, *args, **kwargs): ...
    def omega(self, *args, **kwargs): ...
    def phi(self, *args, **kwargs): ...
    def y(self, *args, **kwargs): ...
