#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

APPLICATIONS="python icoFoam.py" # runParallel expects no spaces in the application name, so we use a variable here

runApplication $APPLICATIONS

# runApplication decomposePar
# runParallel "$APPLICATIONS"
#------------------------------------------------------------------------------
