"""openfoam turbulence package"""

from typing import overload

import pybFoam.pybFoam_core


class singlePhaseTransportModel:
    def __init__(self, U: pybFoam.pybFoam_core.volVectorField, phi: pybFoam.pybFoam_core.surfaceScalarField) -> None: ...

    def correct(self) -> None: ...

class incompressibleTurbulenceModel:
    @staticmethod
    def from_registry(arg: pybFoam.pybFoam_core.fvMesh, /) -> incompressibleTurbulenceModel: ...

    @staticmethod
    def New(U: pybFoam.pybFoam_core.volVectorField, phi: pybFoam.pybFoam_core.surfaceScalarField, transportModel: singlePhaseTransportModel, propertiesName: pybFoam.pybFoam_core.Word = ...) -> incompressibleTurbulenceModel: ...

    def correct(self) -> None: ...

    def U(self) -> pybFoam.pybFoam_core.volVectorField: ...

    def alphaRhoPhi(self) -> pybFoam.pybFoam_core.surfaceScalarField: ...

    def phi(self) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

    def k(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def epsilon(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def omega(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def R(self) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

    @overload
    def nu(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def nu(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def nut(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def nut(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def mu(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def mu(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def mut(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def mut(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def muEff(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def muEff(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def nuEff(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def nuEff(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def devRhoReff(self) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

    @overload
    def devRhoReff(self, arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

    def divDevReff(self, arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

class compressibleTurbulenceModel:
    @staticmethod
    def from_registry(arg: pybFoam.pybFoam_core.fvMesh, /) -> compressibleTurbulenceModel: ...

    def U(self) -> pybFoam.pybFoam_core.volVectorField: ...

    def alphaRhoPhi(self) -> pybFoam.pybFoam_core.surfaceScalarField: ...

    def phi(self) -> pybFoam.pybFoam_core.tmp_surfaceScalarField: ...

    def k(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def epsilon(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def omega(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def R(self) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

    @overload
    def nu(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def nu(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def nut(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def nut(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def mu(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def mu(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def mut(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def mut(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def muEff(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def muEff(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def nuEff(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    @overload
    def nuEff(self, arg: int, /) -> pybFoam.pybFoam_core.tmp_scalarField: ...

    @overload
    def devRhoReff(self) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

    @overload
    def devRhoReff(self, arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_volSymmTensorField: ...

    def divDevRhoReff(self, arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...
