"""finite volume method"""

from typing import overload

import pybFoam.pybFoam_core


@overload
def ddt(vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def ddt(rho: pybFoam.pybFoam_core.dimensionedScalar, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def ddt(rho: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def ddt(alpha: pybFoam.pybFoam_core.volScalarField, rho: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def ddt(vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def ddt(rho: pybFoam.pybFoam_core.dimensionedScalar, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def ddt(rho: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def ddt(alpha: pybFoam.pybFoam_core.volScalarField, rho: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def ddt(vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def ddt(rho: pybFoam.pybFoam_core.dimensionedScalar, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def ddt(rho: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def ddt(alpha: pybFoam.pybFoam_core.volScalarField, rho: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def div(phi: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def div(phi: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def div(phi: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def div(phi: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def div(phi: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.dimensionedScalar, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volScalarField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.dimensionedScalar, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volVectorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.dimensionedScalar, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.dimensionedScalar, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.volTensorField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_volTensorField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.surfaceScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(gamma: pybFoam.pybFoam_core.tmp_surfaceScalarField, vf: pybFoam.pybFoam_core.volSymmTensorField, *, scheme: str | None = None, key: str | None = None, dict: pybFoam.pybFoam_core.dictionary | None = None) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.dimensionedVector, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.tmp_volVectorField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.dimensionedTensor, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...
