"""finite volume method"""

from typing import overload

import pybFoam.pybFoam_core


@overload
def ddt(arg: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, arg2: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def ddt(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, arg2: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def ddt(arg: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def ddt(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, arg2: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def div(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def div(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def div(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def div(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def div(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def laplacian(arg: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.volTensorField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.surfaceScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def laplacian(arg0: pybFoam.pybFoam_core.tmp_surfaceScalarField, arg1: pybFoam.pybFoam_core.volSymmTensorField, /) -> pybFoam.pybFoam_core.tmp_fvSymmTensorMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.dimensionedVector, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.tmp_volVectorField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.dimensionedTensor, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def Su(arg0: pybFoam.pybFoam_core.tmp_volTensorField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def Sp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_fvScalarMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volVectorField, /) -> pybFoam.pybFoam_core.tmp_fvVectorMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.dimensionedScalar, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...

@overload
def SuSp(arg0: pybFoam.pybFoam_core.tmp_volScalarField, arg1: pybFoam.pybFoam_core.volTensorField, /) -> pybFoam.pybFoam_core.tmp_fvTensorMatrix: ...
