"""
openfoam thermo package
"""
from __future__ import annotations
import pybFoam.pybFoam_core
__all__: list[str] = ['basicThermo', 'fluidThermo', 'solidThermo']
class basicThermo:
    @staticmethod
    def from_registry(arg0: pybFoam.pybFoam_core.fvMesh) -> basicThermo:
        ...
    def Cp(self) -> pybFoam.pybFoam_core.tmp_volScalarField:
        ...
    def Cv(self) -> pybFoam.pybFoam_core.tmp_volScalarField:
        ...
    def T(self) -> pybFoam.pybFoam_core.volScalarField:
        ...
    def alphaEff(self, arg0: pybFoam.pybFoam_core.volScalarField) -> pybFoam.pybFoam_core.tmp_volScalarField:
        ...
    def he(self) -> pybFoam.pybFoam_core.volScalarField:
        ...
    def kappa(self) -> pybFoam.pybFoam_core.tmp_volScalarField:
        ...
    def kappaEff(self, arg0: pybFoam.pybFoam_core.volScalarField) -> pybFoam.pybFoam_core.tmp_volScalarField:
        ...
    def p(self) -> pybFoam.pybFoam_core.volScalarField:
        ...
    def rho(self) -> pybFoam.pybFoam_core.tmp_volScalarField:
        ...
class fluidThermo(basicThermo):
    @staticmethod
    def from_registry(arg0: pybFoam.pybFoam_core.fvMesh) -> fluidThermo:
        ...
class solidThermo(basicThermo):
    @staticmethod
    def from_registry(arg0: pybFoam.pybFoam_core.fvMesh) -> solidThermo:
        ...
