"""openfoam thermo package"""

import pybFoam.pybFoam_core


class basicThermo:
    @staticmethod
    def from_registry(arg: pybFoam.pybFoam_core.fvMesh, /) -> basicThermo: ...

    def p(self) -> pybFoam.pybFoam_core.volScalarField: ...

    def T(self) -> pybFoam.pybFoam_core.volScalarField: ...

    def rho(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def he(self) -> pybFoam.pybFoam_core.volScalarField: ...

    def Cp(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def Cv(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def kappa(self) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def kappaEff(self, arg: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

    def alphaEff(self, arg: pybFoam.pybFoam_core.volScalarField, /) -> pybFoam.pybFoam_core.tmp_volScalarField: ...

class fluidThermo(basicThermo):
    @staticmethod
    def from_registry(arg: pybFoam.pybFoam_core.fvMesh, /) -> fluidThermo: ...

class solidThermo(basicThermo):
    @staticmethod
    def from_registry(arg: pybFoam.pybFoam_core.fvMesh, /) -> solidThermo: ...
