name: openfoam

on:
  push:
    branches: [ master ]
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
    - name: setup  openfoam
      run: |
        curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        sudo apt-get install openfoam2106-dev
    - name: compile library
      shell: bash
      run: |
        # setup
        export WM_NCOMPPROCS=2
        python -m pip install --upgrade pip
        
        # similar to build-ECI4FOAM.sh
        pip install -r requirements.txt
        git submodule update --init --recursive
        
        #install generator
        cd OpenFOAMGen/OpenFOAMGen
        conan export . myuser/OpenFOAMGen
        cd ../..

        # compile OpenFOAM
        openfoam2106 -c ./Allwmake

    - name: test
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        openfoam2106 -c "py.test -v --tb=auto -s"

    - name: upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs
