name: openfoam

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ofversion: [openfoam2106, openfoam2112, openfoam2206]
    timeout-minutes: 20

    steps:
    - uses: actions/checkout@v2
      with:
          ofversion: ${{ matrix.ofversion }}
    - name: setup  openfoam
      run: |
        curl -s https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        wget -q -O - https://dl.openfoam.com/add-debian-repo.sh | sudo bash
        sudo apt-get install ${{ matrix.ofversion }}-dev
    - name: compile library
      shell: bash
      run: |
        # setup
        export WM_NCOMPPROCS=2
        python -m pip install --upgrade pip
        
        # compile OpenFOAM
        ${{ matrix.ofversion }} -c ./build-pybFoam.sh

    - name: test
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        ${{ matrix.ofversion }} -c "py.test -v --tb=auto -s"

    - name: upload logs
      if: ${{ failure() }}
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: logs
